# Get all reservations
GET http://localhost:3001/reservations HTTP/1.1
Content-Type: application/json

###

# Create a reservation
POST http://localhost:3001/reservations HTTP/1.1
Content-Type: application/json
userData

###

# Update a reservation
PUT http://localhost:3001/reservations/1 HTTP/1.1
Content-Type: application/json
  userData


###

# Delete a reservation
DELETE http://localhost:3001/reservations/1 HTTP/1.1
Content-Type: application/json

###

# Search a reservation
GET http://localhost:3001/reservations/1 HTTP/1.1
Content-Type: application/json