name: ReactHotelManagement - test

on: [pull_request]

strategy:
      matrix:
        node-version: [18.x, 16.x]

steps:
    - name: Clone repository
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install 

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
        run: npm ci
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint


  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      run: npm test
   